### ISSUE TITLE
Passwords Must Use at Least 6 different Characters

### ISSUE THREAD

**Issue by caceto65** [ExpressInfoSys/EISP#11]
Setup Portal Settings and Saved without error in GP.  
Login/Email - cheryla@expressinfo.com
Password - m091101!
When setting up password in GP, the only prompt was that it must be at least 8 characters, no message regarding 6 different characters.

[Portal Login Error.docx](https://github.com/ExpressInfoSys/EISP/files/1654473/Portal.Login.Error.docx)

**Comment by ewlong** [comment]
Modified settings to force upper, lower and only 3 repeating.
