### ISSUE TITLE
Don't Display Tax Code if YTD = 0.00

### ISSUE THREAD

**Issue by caceto65** [ExpressInfoSys/EISP#20]
[Taxes YTD 0 don't show.docx](https://github.com/ExpressInfoSys/EISP/files/1674795/Taxes.YTD.0.don.t.show.docx)

**Comment by ewlong** [comment]
Fixed, ready for review

**Comment by caceto65** [comment]
Tested and Fixed

**Comment by caceto65** [comment]
Working Now
